
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  datasource:
    password: ghtq345
    host: localhost
    port: 5435
    username: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 300000
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/testexercise0922

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
        format_sql: true
        use_sql_comments: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.xml
    database-change-log-lock-table: DATABASECHANGELOGLOCK
    database-change-log-table: DATABASECHANGELOG
    user: postgres
    password: ghtq345
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/testexercise0922